# Configuration for Hydra
hydra:
  run:
    dir: /tmp/hydra
  job:
    chdir: false

defaults:
  - data_config: heprot.yaml
  - model_config: spectre_tile
  - lr_config: linear_warmup_cos_decay
  - train_config: base
  - wandb_config: base
  - _self_

wandb_config:
  run_name: mean_pe_regression_uni2_featurizer