# Configuration for Hydra
hydra:
  run:
    dir: /tmp/hydra
  job:
    chdir: false

defaults:
  - data_config: spectre_data
  - model_config: pix2pix_unet
  - lr_config: linear_warmup_cos_decay
  - train_config: base
  - wandb_config: base
  - _self_

wandb_config:
  run_name: unet_pix2pix_trial