_target_: spectre.utils.TrainConfig
batch_size: 32
learning_rate: ${lr_config.base_value}
max_epoch_number: 100
num_workers: 16
warmup_epochs: 2
checkpoint_every_n_epochs: 1
profiler: simple
gpu_num: -1